plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

base {
    archivesName = "pisan-commands-${project.mod_version}-mc26.1-26.2"
}

dependencies {
    minecraft "com.mojang:minecraft:${project.modern_minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.modern_fabric_api_version}"
}

sourceSets.main.java.srcDir rootProject.file('shared/src/main/java')

processResources {
    inputs.property 'version', project.mod_version
    filesMatching('fabric.mod.json') {
        expand 'version': project.mod_version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
    withSourcesJar()
}
